### ISSUE TITLE
Live Shipping Fees Estimation Not updating

### ISSUE THREAD

**Issue by kzay** [flagshipcompany/flagship-for-prestashop#1]
Nous constatons que les shippings fees ne sont pas mis a jour lors du changement du nombre d'articles dans le shopping cart.

En navigation privée lors du premier ajout les fees sont calculés, ensuite peut importe que l'on augmente ou diminue la quantité les fees reste ceux précédemment calculé.
Afin qu'il soit de nouveau calculé il faut clear le cache du navigateur.

Meme en cas de suppression et d'ajout de l'item dans le cart les fees ne sont pas remis a jour.

**Comment by radua** [comment]
@kzay Thank you for bringing this to our attention. We have resolved this issue in our latest release. Please remove the plugin entirely and install the latest version.
